//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_dt
    {
        public int Order_dt_id { get; set; }
        public int Order_id { get; set; }
        public string item { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
    }
}
