//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_mt
    {
        public int Order_id { get; set; }
        public string Order_no { get; set; }
        public System.DateTime Order_date { get; set; }
        public string Customer_name { get; set; }
    }
}
